### ISSUE TITLE
Push jobs ssl options not passed on to build nodes

### ISSUE THREAD

**Issue by dreamnite** [chef-cookbooks/delivery-cluster#188]
We have a ssl cerficate signed with an internal CA. There does not seem to be a mechanism in the delivery-cluster cookbook to push a file for the "ssl_ca_file" option, or to push the following override attributes for push-jobs:

```json
"push_jobs": {
        "chef": {
                "verify_api_cert": false,
                "ssl_verify_mode": "verify_none"
         }
        },
```

The certs are places into /chef/trusted-certs but push jobs seems to not honor this.

**Comment by afiune** [comment]
@dreamnite Thank you for reporting this issue. 

There is currently a change in flight that will let you pass these attributes to any component on the cluster. :smile: 

Additionally I can tell you that `push-jobs` does not uses that path to sign the certificates. It uses `/opt/push-jobs-client/embedded/ssl/certs/cacert.pem` so if you want to fix that instead of disabling SSL you can append your CA certs at the end of that file.

Let me know if this works for you. I will also let you know when the change I talked about it is in master.

**Comment by afiune** [comment]
Change just got merged to master. With this change https://github.com/chef-cookbooks/delivery-cluster/commit/083956ac1a44991528b849060434990fb156e7f9 you can pass attributes to disable SSL. :smile: 
 
There are some examples of how it works: https://github.com/chef-cookbooks/delivery-cluster#passing-raw-attributes-to-components

Feel free to reopen this issue if you have doubts of other issue. Thank you so much for the feedback!
