### ISSUE TITLE
Option accept_license must be a kind of [TrueClass, FalseClass]!  You passed "true".

### ISSUE THREAD

**Issue by dreamnite** [chef-cookbooks/delivery-cluster#211]
Getting the above error during "setup:chef_server". 

Json file has:

``` json
  "override_attributes": {
    "delivery-cluster": {
      "accept_license": true,
```

Which should accept the license. I have also attempted adding:

```
 "attributes": {
          "chef-server-12": {
                "accept_license": true,
```

Neither helps.

**Comment by jeremiahsnapp** [comment]
It turned out this was caused by initially setting the attribute to `"true"` which created a `normal` attribute to be set in the node data which overrode the environment default attribute even after fixing the environment default attribute. Deleting the normal attribute from the node data should fix this issue.

**Comment by afiune** [comment]
@dreamnite could you verify what @jeremiahsnapp is proposing?

**Comment by afiune** [comment]
Hit the wrong button 😝 .. apologize

**Comment by dreamnite** [comment]
yes, verified.
